---
name: build_linux

permissions:
  contents: write

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
    branches:
      - main

jobs:
  main:
    runs-on: ${{ matrix.os }}
    name: Ubuntu-${{ matrix.os-name }}-${{ matrix.flutter-arch }} artefacts
    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
            flutter-arch: x64
            dep-depends: libgtk-3-0t64 (>= 3.24.41)
          - os: ubuntu-24.04-arm
            flutter-arch: arm64
            dep-depends: libgtk-3-0t64 (>= 3.24.41)
          - os: ubuntu-22.04
            flutter-arch: x64
            dep-depends: libgtk-3-0 (>= 3.24.33)
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - run: |
          sudo apt update -y
          sudo apt upgrade -y
          sudo apt dist-upgrade -y
      - run: |
          sudo apt install -y ninja-build libgtk-3-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libunwind-dev
      - run: |
          ./linux/oav-custom/compile "${{ matrix.flutter-arch }}" "${{ matrix.deb-depends }}"
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            *.tar.gz
            *.deb

