name: flutter_build

permissions:
  contents: write

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev
      - run: git submodule init
      - run: git submodule update
      - run: echo "$GITHUB_WORKSPACE/.flutter/bin/" >> "$GITHUB_PATH"
      - run: flutter channel stable --disable-analytics
      - run: flutter doctor --verbose
      - run: flutter pub get
      - run: flutter build linux --release
      - run: mv build/linux/x64/release/bundle ./oav-bundle-linux-x86_64
      - run: tar czf oav-bundle-linux-x86_64.tar.gz oav-bundle-linux-x86_64
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            oav-bundle-linux-x86_64.tar.gz
