name: flutter_build

permissions:
  contents: write

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
    branches:
      - main

jobs:
  linux_flutter:
    runs-on: {{ matrix.os }}
    name: Build artefacts for Flathub on Linux, with arch {{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
          - os: ubuntu-24.04-arm
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - run: |
          echo "$GITHUB_WORKSPACE/.flutter/bin/" >> "$GITHUB_PATH"
      - run: |
          sudo apt update -y
          sudo apt dist-upgrade -y
          sudo apt install -y ninja-build libgtk-3-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev
          git submodule init
          git submodule update
          flutter channel stable --disable-analytics
          flutter doctor --verbose
          flutter pub get
          flutter build linux --release
          mv build/linux/{{ matrix.arch }}/release/bundle ./oav-bundle-linux-{{ matrix.arch }}
          tar czf oav-bundle-linux-{{ matrix.arch }}.tar.gz oav-bundle-linux-{{ matrix.arch }}
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            oav-bundle-linux-{{ matrix.arch }}.tar.gz

