name: flutter_build

permissions:
  contents: write

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - run: |
          sudo apt update -y
          sudo apt dist-upgrade -y
          sudo apt install -y ninja-build libgtk-3-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev
          git submodule init
          git submodule update
          echo "$GITHUB_WORKSPACE/.flutter/bin/" >> "$GITHUB_PATH"
          flutter channel stable --disable-analytics
          flutter doctor --verbose
          flutter pub get
          flutter build linux --release
          mv build/linux/x64/release/bundle ./oav-bundle-linux-x86_64
          tar czf oav-bundle-linux-x86_64.tar.gz oav-bundle-linux-x86_64
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            oav-bundle-linux-x86_64.tar.gz
